# Install script for directory: C:/OpenCV_Build/opencv/sources

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/OpenCV_Build/build2/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ippicv-readme.htm" FILES "C:/OpenCV_Build/build2/3rdparty/ippicv/ippicv_win/icv/readme.htm")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ippicv-EULA.rtf" FILES "C:/OpenCV_Build/build2/3rdparty/ippicv/ippicv_win/EULA.rtf")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ippicv-third-party-programs.txt" FILES "C:/OpenCV_Build/build2/3rdparty/ippicv/ippicv_win/third-party-programs.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ippiw-support.txt" FILES "C:/OpenCV_Build/build2/3rdparty/ippicv/ippicv_win/icv/../iw/../support.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ippiw-third-party-programs.txt" FILES "C:/OpenCV_Build/build2/3rdparty/ippicv/ippicv_win/icv/../iw/../third-party-programs.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ippiw-EULA.rtf" FILES "C:/OpenCV_Build/build2/3rdparty/ippicv/ippicv_win/icv/../iw/../EULA.rtf")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "flatbuffers-LICENSE.txt" FILES "C:/OpenCV_Build/opencv/sources/3rdparty/flatbuffers/LICENSE.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "opencl-headers-LICENSE.txt" FILES "C:/OpenCV_Build/opencv/sources/3rdparty/include/opencl/LICENSE.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ade-LICENSE" FILES "C:/OpenCV_Build/build2/3rdparty/ade/ade-0.1.2d/LICENSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ffmpeg-license.txt" FILES "C:/OpenCV_Build/opencv/sources/3rdparty/ffmpeg/license.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE RENAME "ffmpeg-readme.txt" FILES "C:/OpenCV_Build/opencv/sources/3rdparty/ffmpeg/readme.txt")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv2" TYPE FILE FILES "C:/OpenCV_Build/build2/cvconfig.h")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/opencv2" TYPE FILE FILES "C:/OpenCV_Build/build2/opencv2/opencv_modules.hpp")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/x64/vc17/lib/OpenCVModules.cmake")
    file(DIFFERENT _cmake_export_file_changed FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/x64/vc17/lib/OpenCVModules.cmake"
         "C:/OpenCV_Build/build2/CMakeFiles/Export/d30778e0ac7619fb773456bd811156bf/OpenCVModules.cmake")
    if(_cmake_export_file_changed)
      file(GLOB _cmake_old_config_files "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/x64/vc17/lib/OpenCVModules-*.cmake")
      if(_cmake_old_config_files)
        string(REPLACE ";" ", " _cmake_old_config_files_text "${_cmake_old_config_files}")
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/x64/vc17/lib/OpenCVModules.cmake\" will be replaced.  Removing files [${_cmake_old_config_files_text}].")
        unset(_cmake_old_config_files_text)
        file(REMOVE ${_cmake_old_config_files})
      endif()
      unset(_cmake_old_config_files)
    endif()
    unset(_cmake_export_file_changed)
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x64/vc17/lib" TYPE FILE FILES "C:/OpenCV_Build/build2/CMakeFiles/Export/d30778e0ac7619fb773456bd811156bf/OpenCVModules.cmake")
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x64/vc17/lib" TYPE FILE FILES "C:/OpenCV_Build/build2/CMakeFiles/Export/d30778e0ac7619fb773456bd811156bf/OpenCVModules-debug.cmake")
  endif()
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x64/vc17/lib" TYPE FILE FILES "C:/OpenCV_Build/build2/CMakeFiles/Export/d30778e0ac7619fb773456bd811156bf/OpenCVModules-release.cmake")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x64/vc17/lib" TYPE FILE FILES
    "C:/OpenCV_Build/build2/win-install/OpenCVConfig-version.cmake"
    "C:/OpenCV_Build/build2/win-install/x64/vc17/lib/OpenCVConfig.cmake"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE FILES
    "C:/OpenCV_Build/build2/win-install/OpenCVConfig-version.cmake"
    "C:/OpenCV_Build/build2/win-install/OpenCVConfig.cmake"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "libs" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ FILES "C:/OpenCV_Build/opencv/sources/LICENSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "scripts" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE FILES "C:/OpenCV_Build/build2/CMakeFiles/install/setup_vars_opencv4.cmd")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/OpenCV_Build/build2/3rdparty/zlib/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/libjpeg-turbo/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/libtiff/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/libwebp/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/openjpeg/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/libpng/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/openexr/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/ippiw/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/protobuf/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/3rdparty/ittnotify/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/include/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/calib3d/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/core/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/dnn/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/features2d/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/flann/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/gapi/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/highgui/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/imgproc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/java/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/js/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/ml/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/objc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/objdetect/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/photo/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/python/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/stitching/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/ts/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/video/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/videoio/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/world/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/alphamat/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/aruco/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/bgsegm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/bioinspired/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cannops/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/ccalib/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cnn_3dobj/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cudev/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/cvv/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/datasets/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/dnn_objdetect/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/dnn_superres/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/dpm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/face/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/freetype/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/fuzzy/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/hdf/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/hfs/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/img_hash/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/intensity_transform/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/julia/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/line_descriptor/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/matlab/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/mcc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/optflow/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/ovis/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/phase_unwrapping/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/plot/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/quality/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/rapid/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/reg/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/rgbd/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/saliency/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/sfm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/shape/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/stereo/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/structured_light/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/superres/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/surface_matching/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/text/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/tracking/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/videostab/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/viz/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/wechat_qrcode/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/xfeatures2d/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/ximgproc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/xobjdetect/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/.firstpass/xphoto/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudev/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/python_tests/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/core/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudaarithm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/flann/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/imgproc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/intensity_transform/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/ml/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/phase_unwrapping/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/plot/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/quality/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/reg/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/surface_matching/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudafilters/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudaimgproc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudawarping/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/dnn/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/dnn_superres/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/features2d/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/fuzzy/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/hfs/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/img_hash/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/imgcodecs/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/line_descriptor/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/photo/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/saliency/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/text/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/videoio/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/xphoto/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/calib3d/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudacodec/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudafeatures2d/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudastereo/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/datasets/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/highgui/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/mcc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/objdetect/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/rapid/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/rgbd/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/shape/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/structured_light/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/ts/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/video/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/wechat_qrcode/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/xfeatures2d/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/ximgproc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/xobjdetect/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/aruco/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/bgsegm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/bioinspired/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/ccalib/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudabgsegm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudalegacy/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudaobjdetect/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/dnn_objdetect/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/dpm/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/face/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/gapi/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/js_bindings_generator/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/optflow/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/stitching/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/tracking/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/cudaoptflow/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/java_bindings_generator/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/objc_bindings_generator/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/stereo/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/superres/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/videostab/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/python_bindings_generator/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/modules/python3/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/doc/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/data/cmake_install.cmake")
  include("C:/OpenCV_Build/build2/apps/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "C:/OpenCV_Build/build2/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
